<?php
use app\models\Menus;

/**
 *	Used to generate description language keys

 t('path setting description' )
 $t('icon_path setting description' )
 $t('short_path setting description' )
 $t('absolute_path setting description' )
 $t('custom_strings_file setting description' )
 $t('manual_url setting description' )
 $t('session_handler setting description' )
 $t('session_save_path setting description' )
 $t('session_validation setting description' )
 $t('form_security_validation setting description' )
 $t('crypto_master_salt setting description' )
 $t('allow_signup setting description' )
 $t('max_failed_login_count setting description' )
 $t('notify_new_user_created_threshold_min setting description' )
 $t('send_reset_password_on setting description' )
 $t('signup_use_captcha setting description' )
 $t('system_font_folder setting description' )
 $t('font_per_captcha setting description' )
 $t('lost_password_feature setting description' )
 $t('max_lost_password_in_progress_count setting description' )
 $t('webmaster_email setting description' )
 $t('from_email setting description' )
 $t('from_name setting description' )
 $t('return_path_email setting description' )
 $t('enable_email_notifications setting description' )
 $t('default_notify_flags setting description' )
 $t('notify_flags setting description' )
 $t('email_receive_own setting description' )
 $t('validate_email setting description' )
 $t('check_mx_record setting description' )
 $t('allow_blank_email setting description' )
 $t('limit_email_domain setting description' )
 $t('show_user_email_threshold setting description' )
 $t('show_user_realname_threshold setting description' )
 $t('mail_priority setting description' )
 $t('phpMailer_method setting description' )
 $t('smtp_host setting description' )
 $t('smtp_username setting description' )
 $t('smtp_password setting description' )
 $t('smtp_connection_mode setting description' )
 $t('smtp_port setting description' )
 $t('email_send_using_cronjob setting description' )
 $t('email_set_category setting description' )
 $t('email_separator1 setting description' )
 $t('email_separator2 setting description' )
 $t('email_padding_length setting description' )
 $t('show_version setting description' )
 $t('version_suffix setting description' )
 $t('copyright_statement setting description' )
 $t('default_language setting description' )
 $t('language_choices_arr setting description' )
 $t('language_auto_map setting description' )
 $t('fallback_language setting description' )
 $t('window_title setting description' )
 $t('page_title setting description' )
 $t('admin_checks setting description' )
 $t('favicon_image setting description' )
 $t('logo_image setting description' )
 $t('logo_url setting description' )
 $t('reauthentication setting description' )
 $t('reauthentication_expiry setting description' )
 $t('enable_project_documentation setting description' )
 $t('show_footer_menu setting description' )
 $t('show_project_menu_bar setting description' )
 $t('show_assigned_names setting description' )
 $t('show_priority_text setting description' )
 $t('priority_significant_threshold setting description' )

 $t('severity_significant_threshold setting description' )
 $t('view_issues_page_columns setting description' )
 $t('print_issues_page_columns setting description' )
 $t('csv_columns setting description' )
 $t('excel_columns setting description' )
 $t('show_bug_project_links setting description' )
 $t('status_legend_position setting description' )
 $t('status_percentage_legend setting description' )
 $t('filter_position setting description' )
 $t('action_button_position setting description' )
 $t('show_product_version setting description' )
 $t('show_version_dates_threshold setting description' )
 $t('show_realname setting description' )
 $t('differentiate_duplicates setting description' )
 $t('sort_by_last_name setting description' )
 $t('show_avatar setting description' )
 $t('show_avatar_threshold setting description' )
 $t('default_avatar setting description' )
 $t('show_changelog_dates setting description' )
 $t('show_roadmap_dates setting description' )
 $t('cookie_time_length setting description' )
 $t('content_expire setting description' )
 $t('long_process_timeout setting description' )
 $t('short_date_format setting description' )
 $t('normal_date_format setting description' )
 $t('complete_date_format setting description' )
 $t('calendar_js_date_format setting description' )
 $t('calendar_date_format setting description' )
 $t('default_timezone setting description' )
 $t('news_enabled setting description' )
 $t('news_limit_method setting description' )
 $t('news_view_limit setting description' )
 $t('news_view_limit_days setting description' )
 $t('private_news_threshold setting description' )
 $t('default_new_account_access_level setting description' )
 $t('default_bug_view_status setting description' )
 $t('default_bug_steps_to_reproduce setting description' )
 $t('default_bug_additional_info setting description' )
 $t('default_bugnote_view_status setting description' )
 $t('default_bug_resolution setting description' )
 $t('default_bug_severity setting description' )
 $t('default_bug_priority setting description' )
 $t('default_bug_reproducibility setting description' )
 $t('default_bug_projection setting description' )
 $t('default_bug_eta setting description' )
 $t('default_category_for_moves setting description' )
 $t('default_limit_view setting description' )
 $t('default_show_changed setting description' )
 $t('hide_status_default setting description' )
 $t('show_sticky_issues setting description' )
 $t('min_refresh_delay setting description' )
 $t('default_refresh_delay setting description' )
 $t('default_redirect_delay setting description' )
 $t('default_bugnote_order setting description' )
 $t('default_email_on_new setting description' )
 $t('default_email_on_assigned setting description' )
 $t('default_email_on_feedback setting description' )
 $t('default_email_on_resolved setting description' )
 $t('default_email_on_closed setting description' )
 $t('default_email_on_reopened setting description' )
 $t('default_email_on_bugnote setting description' )
 $t('default_email_on_status setting description' )
 $t('default_email_on_priority setting description' )
 $t('default_email_on_new_minimum_severity setting description' )
 $t('default_email_on_assigned_minimum_severity setting description' )
 $t('default_email_on_feedback_minimum_severity setting description' )
 $t('default_email_on_resolved_minimum_severity setting description' )
 $t('default_email_on_closed_minimum_severity setting description' )
 $t('default_email_on_reopened_minimum_severity setting description' )
 $t('default_email_on_bugnote_minimum_severity setting description' )
 $t('default_email_on_status_minimum_severity setting description' )
 $t('default_email_on_priority_minimum_severity setting description' )
 $t('default_email_bugnote_limit setting description' )
 $t('reporter_summary_limit setting description' )
 $t('date_partitions setting description' )
 $t('summary_category_include_project setting description' )
 $t('view_summary_threshold setting description' )
 $t('severity_multipliers setting description' )
 $t('resolution_multipliers setting description' )
 $t('bugnote_order setting description' )
 $t('history_default_visible setting description' )
 $t('history_order setting description' )
 $t('store_reminders setting description' )
 $t('reminder_recipients_monitor_bug setting description' )
 $t('default_reminder_view_status setting description' )
 $t('reminder_receive_threshold setting description' )
 $t('enable_sponsorship setting description' )
 $t('sponsorship_currency setting description' )
 $t('view_sponsorship_total_threshold setting description' )
 $t('view_sponsorship_details_threshold setting description' )
 $t('sponsor_threshold setting description' )
 $t('handle_sponsored_bugs_threshold setting description' )
 $t('assign_sponsored_bugs_threshold setting description' )
 $t('minimum_sponsorship_amount setting description' )
 $t('allow_file_upload setting description' )
 $t('file_upload_method setting description' )
 $t('attachments_file_permissions setting description' )
 $t('file_upload_ftp_server setting description' )
 $t('file_upload_ftp_user setting description' )
 $t('file_upload_ftp_pass setting description' )
 $t('max_file_size setting description' )
 $t('allowed_files setting description' )
 $t('disallowed_files setting description' )
 $t('document_files_prefix setting description' )
 $t('absolute_path_default_upload_folder setting description' )
 $t('file_download_xsendfile_enabled setting description' )
 $t('file_download_xsendfile_header_name setting description' )
 $t('html_make_links setting description' )
 $t('html_valid_tags setting description' )
 $t('html_valid_tags_single_line setting description' )
 $t('max_dropdown_length setting description' )
 $t('wrap_in_preformatted_text setting description' )
 $t('hr_size setting description' )
 $t('hr_width setting description' )
 $t('ldap_server setting description' )
 $t('ldap_root_dn setting description' )
 $t('ldap_organization setting description' )
 $t('ldap_uid_field setting description' )
 $t('ldap_realname_field setting description' )
 $t('ldap_bind_dn setting description' )
 $t('ldap_bind_passwd setting description' )
 $t('use_ldap_email setting description' )
 $t('use_ldap_realname setting description' )
 $t('ldap_protocol_version setting description' )
 $t('ldap_follow_referrals setting description' )
 $t('ldap_simulation_file_path setting description' )
 $t('bug_submit_status setting description' )
 $t('bug_assigned_status setting description' )
 $t('bug_reopen_status setting description' )
 $t('bug_feedback_status setting description' )
 $t('reassign_on_feedback setting description' )
 $t('bug_reopen_resolution setting description' )
 $t('bug_duplicate_resolution setting description' )
 $t('bug_readonly_status_threshold setting description' )
 $t('bug_resolved_status_threshold setting description' )
 $t('bug_resolution_fixed_threshold setting description' )
 $t('bug_resolution_not_fixed_threshold setting description' )
 $t('bug_closed_status_threshold setting description' )
 $t('auto_set_status_to_assigned setting description' )
 $t('status_enum_workflow setting description' )
 $t('fileinfo_magic_db_file setting description' )
 $t('preview_attachments_inline_max_size setting description' )
 $t('preview_text_extensions setting description' )
 $t('preview_image_extensions setting description' )
 $t('preview_max_width setting description' )
 $t('preview_max_height setting description' )
 $t('show_attachment_indicator setting description' )
 $t('view_attachments_threshold setting description' )
 $t('inline_file_exts setting description' )
 $t('download_attachments_threshold setting description' )
 $t('delete_attachments_threshold setting description' )
 $t('allow_view_own_attachments setting description' )
 $t('allow_download_own_attachments setting description' )
 $t('allow_delete_own_attachments setting description' )
 $t('enable_eta setting description' )
 $t('enable_projection setting description' )
 $t('enable_product_build setting description' )
 $t('bug_report_page_fields setting description' )
 $t('bug_view_page_fields setting description' )
 $t('bug_print_page_fields setting description' )
 $t('bug_update_page_fields setting description' )
 $t('bug_change_status_page_fields setting description' )
 $t('report_bug_threshold setting description' )
 $t('update_bug_threshold setting description' )
 $t('monitor_bug_threshold setting description' )
 $t('monitor_add_others_bug_threshold setting description' )
 $t('monitor_delete_others_bug_threshold setting description' )
 $t('private_bug_threshold setting description' )
 $t('handle_bug_threshold setting description' )
 $t('update_bug_assign_threshold setting description' )
 $t('private_bugnote_threshold setting description' )
 $t('view_handler_threshold setting description' )
 $t('view_history_threshold setting description' )
 $t('bug_reminder_threshold setting description' )
 $t('bug_revision_drop_threshold setting description' )
 $t('upload_project_file_threshold setting description' )
 $t('upload_bug_file_threshold setting description' )
 $t('add_bugnote_threshold setting description' )
 $t('update_bugnote_threshold setting description' )
 $t('view_proj_doc_threshold setting description' )
 $t('manage_site_threshold setting description' )
 $t('admin_site_threshold setting description' )
 $t('manage_project_threshold setting description' )
 $t('manage_news_threshold setting description' )
 $t('delete_project_threshold setting description' )
 $t('create_project_threshold setting description' )
 $t('private_project_threshold setting description' )
 $t('project_user_threshold setting description' )
 $t('manage_user_threshold setting description' )
 $t('delete_bug_threshold setting description' )
 $t('delete_bugnote_threshold setting description' )
 $t('move_bug_threshold setting description' )
 $t('set_view_status_threshold setting description' )
 $t('change_view_status_threshold setting description' )
 $t('show_monitor_list_threshold setting description' )
 $t('stored_query_use_threshold setting description' )
 $t('stored_query_create_threshold setting description' )
 $t('stored_query_create_shared_threshold setting description' )
 $t('update_readonly_bug_threshold setting description' )
 $t('view_changelog_threshold setting description' )
 $t('roadmap_view_threshold setting description' )
 $t('roadmap_update_threshold setting description' )
 $t('update_bug_status_threshold setting description' )
 $t('reopen_bug_threshold setting description' )
 $t('report_issues_for_unreleased_versions_threshold setting description' )
 $t('set_bug_sticky_threshold setting description' )
 $t('development_team_threshold setting description' )
 $t('set_status_threshold setting description' )
 $t('bugnote_user_edit_threshold setting description' )
 $t('bugnote_user_delete_threshold setting description' )
 $t('bugnote_user_change_view_state_threshold setting description' )
 $t('allow_no_category setting description' )
 $t('login_method setting description' )
 $t('limit_reporters setting description' )
 $t('allow_reporter_close setting description' )
 $t('allow_reporter_reopen setting description' )
 $t('allow_reporter_upload setting description' )
 $t('allow_account_delete setting description' )
 $t('allow_anonymous_login setting description' )
 $t('anonymous_account setting description' )
 $t('bug_link_tag setting description' )
 $t('bugnote_link_tag setting description' )
 $t('bug_count_hyperlink_prefix setting description' )
 $t('user_login_valid_regex setting description' )
 $t('default_manage_user_prefix setting description' )
 $t('default_manage_tag_prefix setting description' )
 $t('csv_separator setting description' )
 $t('manage_configuration_threshold setting description' )
 $t('view_configuration_threshold setting description' )
 $t('set_configuration_threshold setting description' )
 $t('status_colors setting description' )
 $t('display_project_padding setting description' )
 $t('display_bug_padding setting description' )
 $t('display_bugnote_padding setting description' )
 $t('colour_project setting description' )
 $t('colour_global setting description' )
 $t('cookie_path setting description' )
 $t('cookie_domain setting description' )
 $t('cookie_version setting description' )
 $t('cookie_prefix setting description' )
 $t('string_cookie setting description' )
 $t('project_cookie setting description' )
 $t('view_all_cookie setting description' )
 $t('manage_cookie setting description' )
 $t('logout_cookie setting description' )
 $t('bug_list_cookie setting description' )
 $t('filter_by_custom_fields setting description' )
 $t('filter_custom_fields_per_row setting description' )
 $t('view_filters setting description' )
 $t('use_dynamic_filters setting description' )
 $t('create_permalink_threshold setting description' )
 $t('create_short_url setting description' )
 $t('db_table_prefix setting description' )
 $t('db_table_suffix setting description' )
 $t('access_levels_enum_string setting description' )
 $t('project_status_enum_string setting description' )
 $t('project_view_state_enum_string setting description' )
 $t('view_state_enum_string setting description')
 $t('priority_enum_string setting description' )
 $t('severity_enum_string setting description' )
 $t('reproducibility_enum_string setting description' )
 $t('status_enum_string setting description' )
 $t('resolution_enum_string setting description' )
 $t('projection_enum_string setting description' )
 $t('eta_enum_string setting description' )
 $t('sponsorship_enum_string setting description' )
 $t('custom_field_type_enum_string setting description' )
 $t('use_javascript setting description' )
 $t('compress_html setting description' )
 $t('bottom_include_page setting description' )
 $t('top_include_page setting description' )
 $t('css_include_file setting description' )
 $t('css_rtl_include_file setting description' )
 $t('meta_include_file setting description' )
 $t('default_home_page setting description' )
 $t('logout_redirect_page setting description' )
 $t('custom_headers setting description' )
 $t('allow_browser_cache setting description' )
 $t('allow_file_cache setting description' )
 $t('manage_custom_fields_threshold setting description' )
 $t('custom_field_link_threshold setting description' )
 $t('custom_field_edit_after_create setting description' )
 $t('main_menu_custom_options setting description' )
 $t('file_type_icons setting description' )
 $t('status_icon_arr setting description' )
 $t('sort_icon_arr setting description' )
 $t('unread_icon_arr setting description' )
 $t('my_view_bug_count setting description' )
 $t('my_view_boxes setting description' )
 $t('my_view_boxes_fixed_position setting description' )
 $t('rss_enabled setting description' )
 $t('relationship_graph_enable setting description' )
 $t('dot_tool setting description' )
 $t('neato_tool setting description' )
 $t('relationship_graph_fontname setting description' )
 $t('relationship_graph_fontsize setting description' )
 $t('relationship_graph_orientation setting description' )
 $t('relationship_graph_max_depth setting description' )
 $t('relationship_graph_view_on_click setting description' )
 $t('backward_year_count setting description' )
 $t('forward_year_count setting description' )
 $t('custom_group_actions setting description' )
 $t('wiki_enable setting description' )
 $t('wiki_engine setting description' )
 $t('wiki_root_namespace setting description' )
 $t('wiki_engine_url setting description' )
 $t('recently_visited setting description' )
 $t('recently_visited_count setting description' )
 $t('tag_separator setting description' )
 $t('tag_view_threshold setting description' )
 $t('tag_attach_threshold setting description' )
 $t('tag_detach_threshold setting description' )
 $t('tag_detach_own_threshold setting description' )
 $t('tag_create_threshold setting description' )
 $t('tag_edit_threshold setting description' )
 $t('tag_edit_own_threshold setting description' )
 $t('time_tracking_enabled setting description' )
 $t('time_tracking_with_billing setting description' )
 $t('time_tracking_stopwatch setting description' )
 $t('time_tracking_view_threshold setting description' )
 $t('time_tracking_edit_threshold setting description' )
 $t('time_tracking_reporting_threshold setting description' )
 $t('time_tracking_without_note setting description' )
 $t('enable_profiles setting description' )
 $t('add_profile_threshold setting description' )
 $t('manage_global_profile_threshold setting description' )
 $t('allow_freetext_in_profile_fields setting description' )
 $t('twitter_username setting description' )
 $t('twitter_password setting description' )
 $t('plugins_enabled setting description' )
 $t('plugin_path setting description' )
 $t('manage_plugin_threshold setting description' )
 $t('plugins_force_installed setting description' )
 $t('due_date_update_threshold setting description' )
 $t('due_date_view_threshold setting description' )
 $t('subprojects_inherit_categories setting description' )
 $t('subprojects_inherit_versions setting description' )
 $t('show_timer setting description' )
 $t('show_memory_usage setting description' )
 $t('debug_email setting description' )
 $t('show_queries_count setting description' )
 $t('show_friendly_errors setting description' )
 $t('log_level setting description' )
 $t('log_destination setting description' )
 $t('show_log_threshold setting description' )
*/

$self = $this;

$this->title( $t('Manage Settings page heading title' ) );

$manageMenu = function() use ($self) {
	$manageMenu = Menus::getMenu('manage', array());
	$out = '';
	if( $manageMenu ) {
		$out .= $self->html->htmlMenu($manageMenu['list'], $manageMenu['options']);
	}
	return $out;
};
#print_manage_menu( 'manage_config_page.php' );

# Project Menu Form BEGIN
?>
<?php echo $manageMenu(); ?>
<div class="form-container">
	<h2><?=$t( 'Heading for list of Settings' ); ?></h2>

	<table cellspacing="1" cellpadding="5" border="1">
		<tr class="row-category">
			<td><?=$t('Settings list username column heading')?></td>
			<td><?=$t('Settings list project name column heading')?></td>
			<td><?=$t('Settings list id field column heading')?></td>
			<td><?=$t('Settings list type field column heading')?></td>
			<td><?=$t('Settings list value field column heading')?></td>
			<td><?=$t('Settings list access level required field column heading')?></td>
			<td><?=$t('Settings list actions column heading')?></td>
		</tr><?php

	foreach ( $settings as $setting ) { ?>
		<tr <?php # echo helper_alternate_class() ?>>
			<td><?php #=$setting->user->username?></td>
			<td><?php #$setting->project->name?></td>
			<td><?php #=$setting->id?></td>
			<td><?php #=$setting->type?></td>
			<td><?php #=$setting->value?></td>
			<td><?php #=$setting->access_reqd?></td>
		</tr><?php
	} ?>
	</table>
</div>