<?php
namespace app\controllers;

use lithium\security\Auth;
use lithium\security\Password;
use app\models\Settings;

class SessionsController extends \lithium\action\Controller {

	/**
	 *	@todo Password::check gets further but generates another error.
	 *	it appears that the Auth::check function is checking for a different
	 *	hash than the one generated by Password::check;
	 */
	public function add() {
		$warnings = false;
		$errors = false;
		$returnUrl = false;
		$settings = Settings::all();

		if ($this->request->data && Auth::check('default', $this->request)) {
			return $this->redirect('/');
		}
		# Handle failed authentication attempts
		return compact('settings','returnUrl', 'warnings', 'errors');
	}

	public function delete() {
		Auth::clear('default');
		return $this->redirect('/');
	}
}

?>